FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 5002

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
# RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
# USER appuser

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG configuration=Release
WORKDIR /src
COPY . .

# RUN dotnet restore "CacheLoader.HangFire/CacheLoader.HangFire.csproj"
# COPY . .

# WORKDIR "/src/CacheLoader.HangFire"
# RUN dotnet build "CacheLoader.HangFire.csproj" -c $configuration -o /app/build

RUN dotnet build "Bumblebee.sln" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "CacheLoader.HangFire/CacheLoader.HangFire.csproj" -c $configuration -o /app/publish /p:UseAppHost=false
# RUN dotnet publish "Bumblebee.sln" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
# ENV ASPNETCORE_ENVIRONMENT "UAT"
ENTRYPOINT ["dotnet", "CacheLoader.HangFire.dll"]
