//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Util.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Util.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand and agree to the &lt;a target=&quot;_blank&quot; class=&quot;aLink&quot; href=&quot;/corporate?page=privacypolicy&quot;&gt;Privacy Policy&lt;/a&gt; and &lt;a target=&quot;_blank&quot; class=&quot;aLink&quot; href=&quot;/corporate&quot;&gt;Terms &amp; Conditions&lt;/a&gt; of isango!.
        /// </summary>
        internal static string AcceptsTnC {
            get {
                return ResourceManager.GetString("AcceptsTnC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity operator.
        /// </summary>
        internal static string ActivityOperator {
            get {
                return ResourceManager.GetString("ActivityOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional traveller details.
        /// </summary>
        internal static string AdditionalDetails {
            get {
                return ResourceManager.GetString("AdditionalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address*.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        internal static string adult {
            get {
                return ResourceManager.GetString("adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        internal static string adults {
            get {
                return ResourceManager.GetString("adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount after Discount.
        /// </summary>
        internal static string AfterDiscountLabel {
            get {
                return ResourceManager.GetString("AfterDiscountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Please select currency as GBP/EURO/USD for making payment via AMEX Cards.
        /// </summary>
        internal static string AmexWithGBP {
            get {
                return ResourceManager.GetString("AmexWithGBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount after Discount.
        /// </summary>
        internal static string AmountAfterDiscount {
            get {
                return ResourceManager.GetString("AmountAfterDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount payable.
        /// </summary>
        internal static string amountPayable {
            get {
                return ResourceManager.GetString("amountPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At destination assistance.
        /// </summary>
        internal static string AtDestinationAssistance {
            get {
                return ResourceManager.GetString("AtDestinationAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing address.
        /// </summary>
        internal static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Amount is.
        /// </summary>
        internal static string BookingAmount {
            get {
                return ResourceManager.GetString("BookingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Amount is.
        /// </summary>
        internal static string BookingAmountIs {
            get {
                return ResourceManager.GetString("BookingAmountIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Booking Amount.
        /// </summary>
        internal static string BookingAmountLabel {
            get {
                return ResourceManager.GetString("BookingAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Ref. No.
        /// </summary>
        internal static string BookingRefNo {
            get {
                return ResourceManager.GetString("BookingRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Voucher(s) that we will send within 72 hours.
        /// </summary>
        internal static string BookingVoucher {
            get {
                return ResourceManager.GetString("BookingVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cancellation charges up to {0} hours before the activity. Full charges applicable if canceled within {1} hours..
        /// </summary>
        internal static string CancellationPolicy100ChargableBeforeNhours {
            get {
                return ResourceManager.GetString("CancellationPolicy100ChargableBeforeNhours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% Cancellation charges will be applied if the booking is canceled {1} hours before the travel date..
        /// </summary>
        internal static string CancellationPolicyChargable {
            get {
                return ResourceManager.GetString("CancellationPolicyChargable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation charges will be applied if the booking is canceled {1} hours before the travel date..
        /// </summary>
        internal static string CancellationPolicyChargableWithoutPercentage {
            get {
                return ResourceManager.GetString("CancellationPolicyChargableWithoutPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cancellation charges up to 24 hours before the activity..
        /// </summary>
        internal static string CancellationPolicyDefaultFree24Hours {
            get {
                return ResourceManager.GetString("CancellationPolicyDefaultFree24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cancellation charges before the activity date..
        /// </summary>
        internal static string CancellationPolicyFreeBeforeTravelDate {
            get {
                return ResourceManager.GetString("CancellationPolicyFreeBeforeTravelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cancellation charges up to {0} hours before the activity..
        /// </summary>
        internal static string CancellationPolicyLast {
            get {
                return ResourceManager.GetString("CancellationPolicyLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non- Refundable.
        /// </summary>
        internal static string CancellationPolicyNonRefundable {
            get {
                return ResourceManager.GetString("CancellationPolicyNonRefundable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation policy.
        /// </summary>
        internal static string cancellationpolPay {
            get {
                return ResourceManager.GetString("cancellationpolPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Booking .
        /// </summary>
        internal static string CancelSubject {
            get {
                return ResourceManager.GetString("CancelSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled_en.
        /// </summary>
        internal static string CancelTemplateName {
            get {
                return ResourceManager.GetString("CancelTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card holder name*.
        /// </summary>
        internal static string CardHolder {
            get {
                return ResourceManager.GetString("CardHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number*.
        /// </summary>
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charged amount.
        /// </summary>
        internal static string ChargedAmount {
            get {
                return ResourceManager.GetString("ChargedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Charged Amount.
        /// </summary>
        internal static string ChargedAmountLabel {
            get {
                return ResourceManager.GetString("ChargedAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        internal static string child {
            get {
                return ResourceManager.GetString("child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string childs {
            get {
                return ResourceManager.GetString("childs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred payment option.
        /// </summary>
        internal static string ChoosePaymentOption {
            get {
                return ResourceManager.GetString("ChoosePaymentOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City*.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm booking.
        /// </summary>
        internal static string ConfirmBooking {
            get {
                return ResourceManager.GetString("ConfirmBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact information.
        /// </summary>
        internal static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter required information.
        /// </summary>
        internal static string ContractErr {
            get {
                return ResourceManager.GetString("ContractErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract question.
        /// </summary>
        internal static string ContractQuestion {
            get {
                return ResourceManager.GetString("ContractQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details &amp; payment.
        /// </summary>
        internal static string DetailsPyment {
            get {
                return ResourceManager.GetString("DetailsPyment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Voucher/Gift Voucher.
        /// </summary>
        internal static string DiscountCodeLabel {
            get {
                return ResourceManager.GetString("DiscountCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Voucher/Gift Voucher.
        /// </summary>
        internal static string DiscountVoucher {
            get {
                return ResourceManager.GetString("DiscountVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the QR Code.
        /// </summary>
        internal static string DownLoadQR {
            get {
                return ResourceManager.GetString("DownLoadQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your address.
        /// </summary>
        internal static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter card holder name.
        /// </summary>
        internal static string EnterCardHolder {
            get {
                return ResourceManager.GetString("EnterCardHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter card number.
        /// </summary>
        internal static string EnterCardNumber {
            get {
                return ResourceManager.GetString("EnterCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your city.
        /// </summary>
        internal static string EnterCity {
            get {
                return ResourceManager.GetString("EnterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter lead traveller full name.
        /// </summary>
        internal static string EnterLead {
            get {
                return ResourceManager.GetString("EnterLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter mobile number.
        /// </summary>
        internal static string EnterMobile {
            get {
                return ResourceManager.GetString("EnterMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter security code.
        /// </summary>
        internal static string EnterSecurityCode {
            get {
                return ResourceManager.GetString("EnterSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your post/zip code.
        /// </summary>
        internal static string EnterZip {
            get {
                return ResourceManager.GetString("EnterZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-vouchers will be sent to your email address on &lt;b&gt;7 days before your travel date&lt;/b&gt;. Present these e-vouchers at the park gate to receive your tickets..
        /// </summary>
        internal static string Evoucher7DaysMessage {
            get {
                return ResourceManager.GetString("Evoucher7DaysMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Except.
        /// </summary>
        internal static string Except {
            get {
                return ResourceManager.GetString("Except", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date.
        /// </summary>
        internal static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately we have been unable to process your payment. Please review your credit card details and try again. Or get in touch with our customer service team to complete the booking..
        /// </summary>
        internal static string FailureMsg1 {
            get {
                return ResourceManager.GetString("FailureMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can call our customer service on .
        /// </summary>
        internal static string FailureMsg2 {
            get {
                return ResourceManager.GetString("FailureMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Booking had already been generated so please do not try again. Check your inbox for the confirmation email. Your booking reference number is .
        /// </summary>
        internal static string FailureMsgDuplicateBooking {
            get {
                return ResourceManager.GetString("FailureMsgDuplicateBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Families.
        /// </summary>
        internal static string family {
            get {
                return ResourceManager.GetString("family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please find your voucher attached in PDF format. .
        /// </summary>
        internal static string FindVoucher {
            get {
                return ResourceManager.GetString("FindVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered By isango.
        /// </summary>
        internal static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For products.
        /// </summary>
        internal static string Forproducts {
            get {
                return ResourceManager.GetString("Forproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Cancellation.
        /// </summary>
        internal static string FreeCancellation {
            get {
                return ResourceManager.GetString("FreeCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the acknowledgement. Booking Confirmation will reach you in 15-30 min. If your bank verifies your transaction..
        /// </summary>
        internal static string HeadingConditionalAlternative {
            get {
                return ResourceManager.GetString("HeadingConditionalAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are pleased to acknowledge your booking.
        /// </summary>
        internal static string HeadingConditionalNoAlternate {
            get {
                return ResourceManager.GetString("HeadingConditionalNoAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ignore this e-mail if you have already received a confirmation..
        /// </summary>
        internal static string IgnoreIfAlready {
            get {
                return ResourceManager.GetString("IgnoreIfAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking voucher(s) available to print immediately.
        /// </summary>
        internal static string immediately {
            get {
                return ResourceManager.GetString("immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infant.
        /// </summary>
        internal static string infant {
            get {
                return ResourceManager.GetString("infant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infants.
        /// </summary>
        internal static string infants {
            get {
                return ResourceManager.GetString("infants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You would need Adobe Reader in order to view/print these vouchers, in case  you do not have Adobe Reader, you can download it by &lt;a href=&quot;http://get.adobe.com/reader/&quot;&gt;clicking here &lt;/a&gt;.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead passenger name.
        /// </summary>
        internal static string LeadPassenger {
            get {
                return ResourceManager.GetString("LeadPassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead passenger email.
        /// </summary>
        internal static string LeadPassengerEmail {
            get {
                return ResourceManager.GetString("LeadPassengerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead traveller&apos;s full name*.
        /// </summary>
        internal static string LeadTravellersFullName {
            get {
                return ResourceManager.GetString("LeadTravellersFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead traveller&apos;s first &amp; last name*.
        /// </summary>
        internal static string LeadTravellersName {
            get {
                return ResourceManager.GetString("LeadTravellersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know if you want to make any special request for this product.
        /// </summary>
        internal static string LetUsKnow {
            get {
                return ResourceManager.GetString("LetUsKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead passenger name.
        /// </summary>
        internal static string lp {
            get {
                return ResourceManager.GetString("lp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead passenger email.
        /// </summary>
        internal static string lpe {
            get {
                return ResourceManager.GetString("lpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your hotel details or chosen pick up location.
        /// </summary>
        internal static string MeetingDetails {
            get {
                return ResourceManager.GetString("MeetingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting point.
        /// </summary>
        internal static string MeetingPoint {
            get {
                return ResourceManager.GetString("MeetingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MULTISAVE Discount:.
        /// </summary>
        internal static string MultisaveDiscount {
            get {
                return ResourceManager.GetString("MultisaveDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multisave Discount.
        /// </summary>
        internal static string MultisaveDiscountLabel {
            get {
                return ResourceManager.GetString("MultisaveDiscountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of adults.
        /// </summary>
        internal static string noAdult {
            get {
                return ResourceManager.GetString("noAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of children.
        /// </summary>
        internal static string nochild {
            get {
                return ResourceManager.GetString("nochild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of.
        /// </summary>
        internal static string noOf {
            get {
                return ResourceManager.GetString("noOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of.
        /// </summary>
        internal static string Numberof {
            get {
                return ResourceManager.GetString("Numberof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of adults.
        /// </summary>
        internal static string NumberOfAdults {
            get {
                return ResourceManager.GetString("NumberOfAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of children.
        /// </summary>
        internal static string NumberOfChildren {
            get {
                return ResourceManager.GetString("NumberOfChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of youths.
        /// </summary>
        internal static string NumberOfYouths {
            get {
                return ResourceManager.GetString("NumberOfYouths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Generally we are keen on confirming your bookings instantly – we know you are too! However, for some products we need to revert to our suppliers to check for up to the minute availability status. For such &apos;on request&apos; products we take a maximum of three working days to confirm availability to you.&lt;/p&gt;
        ///                    &lt;p&gt;When you make an &apos;on request&apos; booking, you are confirming your intent of purchase, subject to availability. You authorise payment towards the product, but your card will be charged o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OnRequestDetails {
            get {
                return ResourceManager.GetString("OnRequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option booked.
        /// </summary>
        internal static string OptionBooked {
            get {
                return ResourceManager.GetString("OptionBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Name is.
        /// </summary>
        internal static string OptionName {
            get {
                return ResourceManager.GetString("OptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Name is.
        /// </summary>
        internal static string OptionNameIs {
            get {
                return ResourceManager.GetString("OptionNameIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be charged on Confirmation of Pending Booking Requests.
        /// </summary>
        internal static string OrAmountLabel {
            get {
                return ResourceManager.GetString("OrAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Price:.
        /// </summary>
        internal static string OriginalPrice {
            get {
                return ResourceManager.GetString("OriginalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Confirmation.
        /// </summary>
        internal static string PendingConfirmation {
            get {
                return ResourceManager.GetString("PendingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Confirmation.
        /// </summary>
        internal static string PendingConfirmation1 {
            get {
                return ResourceManager.GetString("PendingConfirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept terms and conditions.
        /// </summary>
        internal static string PleaseAccept {
            get {
                return ResourceManager.GetString("PleaseAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note this is a receipt of your booking and cannot be redeemed for any service..
        /// </summary>
        internal static string pleaseNote {
            get {
                return ResourceManager.GetString("pleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note this is a receipt of your booking and cannot be redeemed for any service..
        /// </summary>
        internal static string PleaseNote1 {
            get {
                return ResourceManager.GetString("PleaseNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A copy of this receipt has been sent to your mail..
        /// </summary>
        internal static string PleaseNoteAlternative {
            get {
                return ResourceManager.GetString("PleaseNoteAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A copy of this receipt has been sent to your mail..
        /// </summary>
        internal static string PleaseNoteAlternative1 {
            get {
                return ResourceManager.GetString("PleaseNoteAlternative1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Note.
        /// </summary>
        internal static string Pleasenotes {
            get {
                return ResourceManager.GetString("Pleasenotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide correct transfer details.
        /// </summary>
        internal static string PleaseProvide {
            get {
                return ResourceManager.GetString("PleaseProvide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Please wait while we process your booking...&lt;/b&gt;
        ///                        &lt;p&gt;This may take up to 1 minute. Please do not click untill the next page appears.&lt;/p&gt;.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostCode*.
        /// </summary>
        internal static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please print all the pages of the vouchers and carry them to the meeting point/pickup location.
        /// </summary>
        internal static string PrintText {
            get {
                return ResourceManager.GetString("PrintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must print your voucher.  Unfortunately our local suppliers are not able to accept vouchers shown on smartphones or other devices..
        /// </summary>
        internal static string PrintTextSmartPhone {
            get {
                return ResourceManager.GetString("PrintTextSmartPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we process your booking....
        /// </summary>
        internal static string ProcessBooking1 {
            get {
                return ResourceManager.GetString("ProcessBooking1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may take up to 1 minute. Please do not click untill the next page appears..
        /// </summary>
        internal static string ProcessBooking2 {
            get {
                return ResourceManager.GetString("ProcessBooking2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        internal static string ProductName1 {
            get {
                return ResourceManager.GetString("ProductName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product On Request.
        /// </summary>
        internal static string ProductOnRequest {
            get {
                return ResourceManager.GetString("ProductOnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will be sending you a separate voucher for this ticket..
        /// </summary>
        internal static string ReceiptMessage {
            get {
                return ResourceManager.GetString("ReceiptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-voucher(s) will be sent to your email address in the next &lt;span&gt;24&lt;/span&gt; hours. Detailed redemption instructions will appear on the e-vouchers..
        /// </summary>
        internal static string redemption {
            get {
                return ResourceManager.GetString("redemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Ref. No. for further correspondence..
        /// </summary>
        internal static string RefNoText {
            get {
                return ResourceManager.GetString("RefNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know if you want to make any special request for this product.
        /// </summary>
        internal static string reqText {
            get {
                return ResourceManager.GetString("reqText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALE Discount:.
        /// </summary>
        internal static string SaleDiscount {
            get {
                return ResourceManager.GetString("SaleDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure card payment.
        /// </summary>
        internal static string SecureCard {
            get {
                return ResourceManager.GetString("SecureCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code*.
        /// </summary>
        internal static string SecurityCode {
            get {
                return ResourceManager.GetString("SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your country.
        /// </summary>
        internal static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select expiry month.
        /// </summary>
        internal static string SelectExpiryMonth {
            get {
                return ResourceManager.GetString("SelectExpiryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior.
        /// </summary>
        internal static string senior {
            get {
                return ResourceManager.GetString("senior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seniors.
        /// </summary>
        internal static string seniors {
            get {
                return ResourceManager.GetString("seniors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Voucher(s) that we will send 7 days before of travel date.
        /// </summary>
        internal static string SevenDaysMessage {
            get {
                return ResourceManager.GetString("SevenDaysMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special request &lt;span&gt;(if any)&lt;/span&gt;.
        /// </summary>
        internal static string SpecialRequest {
            get {
                return ResourceManager.GetString("SpecialRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inform us about any special requests you may have regarding this product..
        /// </summary>
        internal static string SplReqPlaceHolder {
            get {
                return ResourceManager.GetString("SplReqPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MULTISAVE Discount:.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Voucher.
        /// </summary>
        internal static string SupplierVoucher {
            get {
                return ResourceManager.GetString("SupplierVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        internal static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email_en.
        /// </summary>
        internal static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string TnC {
            get {
                return ResourceManager.GetString("TnC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand and agree to the.
        /// </summary>
        internal static string TnC1 {
            get {
                return ResourceManager.GetString("TnC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand and agree to the &lt;a target=&quot;_blank&quot; class=&quot;aLink&quot; href=&quot;/privacy-policy&quot;&gt;Privacy Policy&lt;/a&gt; and &lt;a target=&quot;_blank&quot; class=&quot;aLink&quot; href=&quot;/booking-agreement&quot;&gt;Terms &amp; Conditions&lt;/a&gt; of isango!.
        /// </summary>
        internal static string TnCcontent {
            get {
                return ResourceManager.GetString("TnCcontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand and agree to the &lt;a target=&quot;_blank&quot; class=&quot;aLink&quot; href=&quot;/corporate?page=privacypolicy&quot;&gt;Privacy Policy&lt;/a&gt; and &lt;a target=&quot;_blank&quot; class=&quot;aLink&quot; href=&quot;/corporate&quot;&gt;Terms &amp; Conditions&lt;/a&gt; of isango!.
        /// </summary>
        internal static string TnCcontentIsango {
            get {
                return ResourceManager.GetString("TnCcontentIsango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be Charged on Confirmation of Pending Booking Requests.
        /// </summary>
        internal static string TobeCharged {
            get {
                return ResourceManager.GetString("TobeCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be Charged on Confirmation of Pending Booking Requests.
        /// </summary>
        internal static string ToBeChargedAmount {
            get {
                return ResourceManager.GetString("ToBeChargedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be confirmed within 72 hours.
        /// </summary>
        internal static string toBeConfirmed {
            get {
                return ResourceManager.GetString("toBeConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Booking Amount.
        /// </summary>
        internal static string TotalBookingAmount {
            get {
                return ResourceManager.GetString("TotalBookingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cart value.
        /// </summary>
        internal static string TotalCartValue {
            get {
                return ResourceManager.GetString("TotalCartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Charged Amount.
        /// </summary>
        internal static string TotalChargedAmount {
            get {
                return ResourceManager.GetString("TotalChargedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel date.
        /// </summary>
        internal static string traveldate {
            get {
                return ResourceManager.GetString("traveldate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel date.
        /// </summary>
        internal static string TravelDate1 {
            get {
                return ResourceManager.GetString("TravelDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand and agree to the.
        /// </summary>
        internal static string understanandagree {
            get {
                return ResourceManager.GetString("understanandagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal booking amount notification. Booking reference no is.
        /// </summary>
        internal static string UniversalBooking {
            get {
                return ResourceManager.GetString("UniversalBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal booking amount notification. Booking reference no is.
        /// </summary>
        internal static string UniversalBookingAmount {
            get {
                return ResourceManager.GetString("UniversalBookingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid card number.
        /// </summary>
        internal static string validCartNumber {
            get {
                return ResourceManager.GetString("validCartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to print the vouchers (PDF format).
        /// </summary>
        internal static string VoucherLink {
            get {
                return ResourceManager.GetString("VoucherLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send a separate voucher for this product.
        /// </summary>
        internal static string WeWillSend {
            get {
                return ResourceManager.GetString("WeWillSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is this?.
        /// </summary>
        internal static string WhatIsThis {
            get {
                return ResourceManager.GetString("WhatIsThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code? The card security code is a unique three or four-digit number printed on your debit/credit card. This number is not embossed on the card and hence not printed on receipts - making it difficult for anyone other than the genuine cardholder,to know it. Some card issuers refer to this number as the &apos;Card Security Code&apos; others as the &apos;Personal Security Code&apos;and others as &apos;Card Verification Value&apos;..
        /// </summary>
        internal static string WhatIsThis1 {
            get {
                return ResourceManager.GetString("WhatIsThis1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa, Mastercard and Maestro Card:.
        /// </summary>
        internal static string WhatIsThis2 {
            get {
                return ResourceManager.GetString("WhatIsThis2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most cards have a set of numbers printed at the top of the signature strip on the reverse of the card, the final three-digit number is your security code..
        /// </summary>
        internal static string WhatIsThis3 {
            get {
                return ResourceManager.GetString("WhatIsThis3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card verification code for American Express:.
        /// </summary>
        internal static string WhatIsThis4 {
            get {
                return ResourceManager.GetString("WhatIsThis4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 4 digit number on the front of the card is your CVV code for American Express cards..
        /// </summary>
        internal static string WhatIsThis5 {
            get {
                return ResourceManager.GetString("WhatIsThis5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the activity operates.
        /// </summary>
        internal static string WhenActivityOperates {
            get {
                return ResourceManager.GetString("WhenActivityOperates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the activity operates.
        /// </summary>
        internal static string WhenTheActivityOperates {
            get {
                return ResourceManager.GetString("WhenTheActivityOperates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Voucher(s) that we will send within 24 hours.
        /// </summary>
        internal static string withinin48 {
            get {
                return ResourceManager.GetString("withinin48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Booking Detail.
        /// </summary>
        internal static string YourBookingDetail {
            get {
                return ResourceManager.GetString("YourBookingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact information.
        /// </summary>
        internal static string YourContactInfo {
            get {
                return ResourceManager.GetString("YourContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Order.
        /// </summary>
        internal static string yourorder {
            get {
                return ResourceManager.GetString("yourorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Order.
        /// </summary>
        internal static string YourOrder1 {
            get {
                return ResourceManager.GetString("YourOrder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-voucher(s) will be sent to your email address in the next &lt;span&gt;72&lt;/span&gt; hours. Detailed redemption instructions will appear on the e-vouchers..
        /// </summary>
        internal static string YourVoucher {
            get {
                return ResourceManager.GetString("YourVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will recieve a booking confirmation in the next 30 minutes on successful transaction  verification by your bank.
        /// </summary>
        internal static string YourVoucherAlternative {
            get {
                return ResourceManager.GetString("YourVoucherAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will recieve a booking confirmation in the next 30 minutes on successful transaction  verification by your bank.
        /// </summary>
        internal static string YourVoucherAlternative1 {
            get {
                return ResourceManager.GetString("YourVoucherAlternative1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth.
        /// </summary>
        internal static string youth {
            get {
                return ResourceManager.GetString("youth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youths.
        /// </summary>
        internal static string youths {
            get {
                return ResourceManager.GetString("youths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you will receive separate vouchers once they are confirmed by our local partners. You would need to take a print out once you receive the confirmation and present it to our local partner in order to redeem your tour.
        /// </summary>
        internal static string YouWillRecieve {
            get {
                return ResourceManager.GetString("YouWillRecieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yrs.
        /// </summary>
        internal static string yrs {
            get {
                return ResourceManager.GetString("yrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case our database cannot populate your address then please type in your address.
        /// </summary>
        internal static string ZipNotFound {
            get {
                return ResourceManager.GetString("ZipNotFound", resourceCulture);
            }
        }
    }
}
