namespace ServiceAdapters.HotelBeds.Constants
{
    public sealed class Constant
    {
        public const string XmlRequest = "xml_request";
        public const string EndWithRelease = "release\\";
        public const string HotelValuedAvailRqDynamic = "\\HotelValuedAvailRQDynamic.xml";
        public const string HotelValuedAvailRq = "\\HotelValuedAvailRQ.xml";
        public const string HBHotelValuedAvailRq = "//hb:HotelValuedAvailRQ";
        public const string RqDateFormat = "i!yyyyMMdd@HH:mm.ss";
        public const string HotelValuedAvailRqLang = "//hb:HotelValuedAvailRQ/hb:Language";
        public const string HotelValuedAvailRqUser = "//hb:HotelValuedAvailRQ/hb:Credentials/hb:User";
        public const string HotelValuedAvailRqPwd = "//hb:HotelValuedAvailRQ/hb:Credentials/hb:Password";
        public const string HotelValuedAvailRqPagination = "//hb:HotelValuedAvailRQ/hb:PaginationData";
        public const string ItemsPerPage = "itemsPerPage";
        public const string HotelValuedAvailRqCid = "/hb:HotelValuedAvailRQ/hb:CheckInDate";
        public const string HotelValuedAvailRqCod = "/hb:HotelValuedAvailRQ/hb:CheckOutDate";
        public const string Date = "date";
        public const string Code = "code";
        public const string CheckInOutFormat = "yyyyMMdd";
        public const string Par = "PAR";
        public const string HotelValuedAvailRqDest = "/hb:HotelValuedAvailRQ/hb:Destination";
        public const string HotelValuedAvailRqCheckOut = "/hb:HotelValuedAvailRQ/hb:CheckOutDate";
        public const string HotelValuedAvailRqHotelCodeList = "//hb:HotelValuedAvailRQ/hb:HotelCodeList";
        public const string AdultCount = "/hb:HotelValuedAvailRQ/hb:OccupancyList/hb:HotelOccupancy/hb:Occupancy/hb:AdultCount";
        public const string ChildCount = "/hb:HotelValuedAvailRQ/hb:OccupancyList/hb:HotelOccupancy/hb:Occupancy/hb:ChildCount";
        public const string Occupancy = "/hb:HotelValuedAvailRQ/hb:OccupancyList/hb:HotelOccupancy/hb:Occupancy";
        public const string GuestList = "GuestList";
        public const string GuestListStartTag = "<GuestList>";
        public const string GuestListEndTag = "</GuestList>";
        public const string ProductCodeStart = "<ProductCode>";
        public const string ProductCodeEnd = "</ProductCode>";
        public const string Language = "Language";
        public const string Customer = "Customer";
        public const string Age = "Age";
        public const string CustomerId = "CustomerId";
        public const string OnRequest = "onRequest";
        public const string CancellationPolicy = "CancellationPolicy";
        public const string DateTimeFrom = "DateTimeFrom";
        public const string DateTimeTo = "DateTimeTo";
        public const string ExceptionMsg1 = "There's no HotelBeds Ticket in cart.";
        public const string ServiceAddRqHotel = "\\ServiceAddRQ_Hotel.xml";
        public const string Debug = "debug\\";
        public const string IsangoHB = "isango!HB";
        public const string User = "User";
        public const string Password = "Password";
        public const string CustomerTypeStart = "<Customer type=\"";
        public const string CustomerTypeEnd = "</Customer>";
        public const string CustomerIdStart = "<CustomerId>";
        public const string CustomerIdEnd = "</CustomerId>";
        public const string AgeStart = "<Age>";
        public const string AgeEnd = "</Age>";
        public const string NameStart = "<Name>";
        public const string NameEnd = "</Name>";
        public const string LastNameStart = "<LastName>";
        public const string LastNameEnd = "</LastName>";
        public const string Release = "release\\";
        public const string TicketAvailRq = "//hb:TicketAvailRQ";
        public const string ProductTicket = "xsi:type=\"ProductTicket\"";
        public const string HbServiceUrl = "HBServiceURL";
        public const string HotelValuedAvailRqDynamicXml = "\\xml\\HotelValuedAvailRQDynamic.xml";
        public const string HotelValuedAvailRqXml = "\\xml\\HotelValuedAvailRQ.xml";
        public const string Hb = "hb";
        public const string Ch = "CH";
        public const string In = "IN";
        public const string Yu = "YU";
        public const string CancellationPolicyList = "CancellationPolicyList";
        public const string ServiceDetailList = "ServiceDetailList";
        public const string ServiceDetail = "ServiceDetail";
        public const string TicketValuationRqXml = "\\xml\\TicketValuationRQ.xml";
        public const string TicketValuationRq = "\\TicketValuationRQ.xml";
        public const string AvailToken = "AvailToken";
        public const string Ad = "AD";
        public const string Time = "time";
        public const string Hotel = "hotel";
        public const string Type = "xsi:type";
        public const string CancellationPolicies = "CancellationPolicies";
        public const string PriceRangeList = "PriceRangeList";
        public const string ServiceAddTicketXml = "\\xml\\ServiceAdd_Ticket.xml";
        public const string ServiceAddTicket = "\\ServiceAdd_Ticket.xml";
        public const string ServiceAddRqHbService = "//hb:ServiceAddRQ/hb:Service";
        public const string SeatingShoppingCartId = "//hb:SeatingShoppingCartId";
        public const string PurchaseCancelRqXml = "\\xml\\PurchaseCancelRQ.xml";
        public const string PurchaseReference = "PurchaseReference";
        public const string HotelOption = "HotelOption";
        public const string CommentList = "CommentList";
        public const string AdditionalCost = "AdditionalCost";
        public const string Amount = "amount";
        public const string DateFrom = "dateFrom";
        public const string PurchaseConfirmRqXml = "\\xml\\PurchaseConfirmRQ.xml";
        public const string HBPurchaseConfirmRq = "//hb:PurchaseConfirmRQ";
        public const string HbPurchaseConfirmRqHbCredentialsHbUser = "//hb:PurchaseConfirmRQ/hb:Credentials/hb:User";
        public const string HbPurchaseConfirmRqHbCredentialsHbPassword = "//hb:PurchaseConfirmRQ/hb:Credentials/hb:Password";
        public const string HbPurchaseConfirmRqHbConfirmationData = "//hb:PurchaseConfirmRQ/hb:ConfirmationData";
        public const string HbPurchaseConfirmRqHbConfirmatioDataHolderName = "//hb:PurchaseConfirmRQ/hb:ConfirmationData/hb:Holder/hb:Name";
        public const string HbPurchaseConfirmRqHbConfirmatioDataHolderLastName = "//hb:PurchaseConfirmRQ/hb:ConfirmationData/hb:Holder/hb:LastName";

        public const string HbPurchaseConfirmRqServiceData =
            "//hb:PurchaseConfirmRQ/hb:ConfirmationData/hb:ConfirmationServiceDataList/hb:ServiceData";

        public const string LastName = "LastName";
        public const string PurchaseDetailRqXml = "\\xml\\PurchaseDetailRQ.xml";
        public const string ServiceRemoveRqXml = "\\ServiceRemoveRQ.xml";
        public const string ServiceRemoveRq = "ServiceRemoveRQ";
        public const string TicketAvailRqXml = "\\xml\\TicketAvailRQ.xml";
        public const string TicketAvailRqLanguage = "//hb:TicketAvailRQ/hb:Language";
        public const string TicketAvailRqCredentialsUser = "//hb:TicketAvailRQ/hb:Credentials/hb:User";
        public const string TicketAvailRqCredentialsPassword = "//hb:TicketAvailRQ/hb:Credentials/hb:Password";
        public const string TicketAvailRqDateFrom = "/hb:TicketAvailRQ/hb:DateFrom";
        public const string TicketAvailRqDateTo = "/hb:TicketAvailRQ/hb:DateTo";
        public const string TicketAvailRqDestination = "/hb:TicketAvailRQ/hb:Destination";
        public const string TicketAvailRqFactsheetFilter = "/hb:TicketAvailRQ/hb:FactsheetFilter";
        public const string TicketAvailRqServiceOccupancyAdultCount = "/hb:TicketAvailRQ/hb:ServiceOccupancy/hb:AdultCount";
        public const string TicketAvailRqServiceOccupancyChildCount = "/hb:TicketAvailRQ/hb:ServiceOccupancy/hb:ChildCount";
        public const string TicketAvailRqServiceOccupancy = "/hb:TicketAvailRQ/hb:ServiceOccupancy";
        public const string ChildInnerText = "21";
        public const string StartFactsheet = "<Factsheet>";
        public const string EndFactsheet = "</Factsheet>";
        public const string PurchaseCancelRq = "\\xml\\PurchaseCancelRQ.xml";
        public const string PurchaseConfirmRqTicketXml = "\\xml\\PurchaseConfirmRQ_Ticket.xml";
        public const string PurchaseConfirmRqLanguage = "//hb:PurchaseConfirmRQ/hb:Language";
        public const string PurchaseConfirmRqUser = "//hb:PurchaseConfirmRQ/hb:Credentials/hb:User";
        public const string PurchaseConfirmRqPassword = "//hb:PurchaseConfirmRQ/hb:Credentials/hb:Password";
        public const string PurchaseConfirmRqConfirmationData = "//hb:PurchaseConfirmRQ/hb:ConfirmationData";
        public const string PurchaseConfirmRqConfirmationServiceDataList = "//hb:PurchaseConfirmRQ/hb:ConfirmationData/hb:ConfirmationServiceDataList";
        public const string PurchaseConfirmRqServiceData = "<ServiceData xsi:type=\"ConfirmationServiceDataTicket\" SPUI=\"";
        public const string PurchaseConfirmRqServiceDataHotel = "<ServiceData xsi:type=\"ConfirmationServiceDataHotel\" SPUI=\"";
        public const string StartCustomerList = "<CustomerList>";
        public const string EndCustomerList = "\n</CustomerList>";
        public const string StartServiceDetailList = "<ServiceDetailList>";
        public const string EndServiceDetailList = "\n</ServiceDetailList>";
        public const string ServiceData = "</ServiceData>";
        public const string ServiceDetailCode = "<ServiceDetail code=\"";
        public const string StartDescription = "<Description>";
        public const string EndDescription = "</Description>";
        public const string EndServiceDeatail = "</ServiceDetail>";
        public const string TicketOfficePriceDesc = "TICKET OFFICE PRICE";
        public const string ChildTicketOfficePriceDesc = "CHILD TICKET OFFICE PRICE";
        public const string ServicePriceDesc = "SERVICE PRICE";
    }
}